// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerInfo1 : byte
{
   Softcore = 1,
   Mediumcore = 2,
   Hardcore = 4,
   ExtraAccessory = 8,
   Creative = 16,
}
