// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerInfo2 : byte
{
   UsingBiomeTorches = 1,
   HappyTorchTime = 2,
   UnlockedBiomeTorches = 4,
   UnlockedSuperCart = 8,
   EnabledSuperCart = 16,
}
