// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerInfo3 : byte
{
   UsedAegisCrystal = 1,
   UsedAegisFruit = 2,
   UsedArcaneCrystal = 4,
   UsedGalaxyPearl = 8,
   UsedGummyWorm = 16,
   UsedAmbrosia = 32,
   AteArtisanBread = 64,
}
