// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerControls1 : byte
{
   Up = 1,
   Down = 2,
   Left = 4,
   Right = 8,
   Jump = 16,
   UseItem = 32,
   Direction = 64,
}
