// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerControls4 : byte
{
   IsSleeping = 1,
   AutoReuseAllWeapons = 2,
   ControlDownHold = 4,
   IsOperatingAnotherEntity = 8,
   ControlUseTile = 16,
}
