// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerControls2 : byte
{
   PulleyActive = 1,
   PulleyDir = 2,
   VortexStealth = 4,
   GravityDirection = 8,
   Shield = 16,
   Ghost = 32,
}
