// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum PlayerControls3 : byte
{
   HoveringUp = 1,
   VoidVaultEnabled = 2,
   IsSitting = 4,
   DownedDD2Event = 8,
   IsPettingAnimal = 16,
   IsAnimalBeingSmall = 32,
   UsedPotionOfReturn = 64,
   HoveringDown = 128,
}
