// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo5 : byte
{
   DownedPirates = 1,
   DownedFrost = 2,
   DownedGoblins = 4,
   SandstormHappening = 8,
   DD2Onging = 16,
   DD2DownedInvasionT1 = 32,
   DD2DownedInvasionT2 = 64,
   DD2DownedInvasionT3 = 128,
}
