// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo7 : byte
{
   BoughtCat = 1,
   BoughtDog = 2,
   BoughtBunny = 4,
   FreeCake = 8,
   DrunkWorld = 16,
   DownedEmpressOfLight = 32,
   DownedQueenSlime = 64,
   GetGoodWorld = 128,
}
