// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo3 : byte
{
   FastForwardTimeToDawn = 1,
   DownedSlimeKing = 2,
   DownedQueenBee = 4,
   DownedFishron = 8,
   DownedMartians = 16,
   DownedAncientCultist = 32,
}
