// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo4 : byte
{
   DownedMoonlord = 1,
   DownedHalloweenKing = 2,
   DownedHalloweenTree = 4,
   DownedChristmasIceQueen = 8,
   DownedChristmasSantaNK = 16,
   DownedChristmasTree = 32,
   DownedGolem = 64,
   BirthdayManualParty = 128,
}
