// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo1 : byte
{
   DownedBoss1 = 1,
   DownedBoss2 = 2,
   DownedBoss3 = 4,
   HardMode = 8,
   DownedClown = 16,
   ServerSideCharacters = 32,
   DownedPlantBoss = 64,
}
