// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo9 : byte
{
   UnlockedGreenSlime = 1,
   UnlockedOldSlime = 2,
   UnlockedPurpleSlime = 4,
   UnlockedRainbowSlime = 8,
   UnlockedRedSlime = 16,
   UnlockedYellowSlime = 32,
   UnlockedCopperSlime = 64,
   FastForwardTimeToDusk = 128,
}
