// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo6 : byte
{
   CombatBookUsed = 1,
   ManualLanterns = 2,
   DownedSolarTower = 4,
   DownedVortexTower = 8,
   DownedNebulaTower = 16,
   DownedStardustTower = 32,
   ForcedHalloween = 64,
   ForcedXMas = 128,
}
