// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo2 : byte
{
   DownedMechBoss1 = 1,
   DownedMechBoss2 = 2,
   DownedMechBoss3 = 4,
   DownedMechBossAny = 8,
   CloudBGActive = 16,
   Crimson = 32,
   PumpkinMoon = 64,
   SnowMoon = 128,
}
