// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo8 : byte
{
   TenthAnniversary = 1,
   DontStarveWorld = 2,
   DownedDeerclops = 4,
   NotTheBessWorld = 8,
   RemixWorld = 16,
   UnlockedSlimeBlueSpawn = 32,
   CombatBookV2Used = 64,
   PeddlersSatchelUsed = 128,
}
