// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Models;

[Flags]
public enum WorldInfo10 : byte
{
   NoTrapsWorld = 1,
   ZenithWorld = 2,
   UnlockedTruffleSpawn = 4,
}
