// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ChestPlaceOrBreakPacket : IPacket<ChestPlaceOrBreak>
{
   public int PacketID => 34;
   public ChestPlaceOrBreak Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte interactionId = reader.ReadByte();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Int16 arg1 = reader.ReadInt16();
       Int16 arg2 = reader.ReadInt16();
       
       return new()
       {
           InteractionId = interactionId,
           X = x,
           Y = y,
           Arg1 = arg1,
           Arg2 = arg2,
       };
   }
   public byte[] Serialize(ChestPlaceOrBreak data)
   {
       return new PacketWriter().SetType(34)
           .PackByte(data.InteractionId)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackInt16(data.Arg1)
           .PackInt16(data.Arg2)
           .BuildPacket();
   }
}
 
public struct ChestPlaceOrBreak
{
   public Byte InteractionId;
   public Int16 X;
   public Int16 Y;
   public Int16 Arg1;
   public Int16 Arg2;
}
