// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ChestTryOpenPacket : IPacket<ChestTryOpen>
{
   public int PacketID => 31;
   public ChestTryOpen Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       
       return new()
       {
           X = x,
           Y = y,
       };
   }
   public byte[] Serialize(ChestTryOpen data)
   {
       return new PacketWriter().SetType(31)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .BuildPacket();
   }
}
 
public struct ChestTryOpen
{
   public Int16 X;
   public Int16 Y;
}
