// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ChestPutItemInPacket : IPacket<ChestPutItemIn>
{
   public int PacketID => 32;
   public ChestPutItemIn Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 chestIndex = reader.ReadInt16();
       Byte chestSlot = reader.ReadByte();
       Int16 itemStack = reader.ReadInt16();
       Byte itemPrefix = reader.ReadByte();
       Int16 itemType = reader.ReadInt16();
       
       return new()
       {
           ChestIndex = chestIndex,
           ChestSlot = chestSlot,
           ItemStack = itemStack,
           ItemPrefix = itemPrefix,
           ItemType = itemType,
       };
   }
   public byte[] Serialize(ChestPutItemIn data)
   {
       return new PacketWriter().SetType(32)
           .PackInt16(data.ChestIndex)
           .PackByte(data.ChestSlot)
           .PackInt16(data.ItemStack)
           .PackByte(data.ItemPrefix)
           .PackInt16(data.ItemType)
           .BuildPacket();
   }
}
 
public struct ChestPutItemIn
{
   public Int16 ChestIndex;
   public Byte ChestSlot;
   public Int16 ItemStack;
   public Byte ItemPrefix;
   public Int16 ItemType;
}
