// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ChestSetNameValidPacket : IPacket<ChestSetNameValid>
{
   public int PacketID => 69;
   public ChestSetNameValid Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 chestIndex = reader.ReadInt16();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       String name = reader.ReadString();
       
       return new()
       {
           ChestIndex = chestIndex,
           X = x,
           Y = y,
           Name = name,
       };
   }
   public byte[] Serialize(ChestSetNameValid data)
   {
       return new PacketWriter().SetType(69)
           .PackInt16(data.ChestIndex)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackString(data.Name)
           .BuildPacket();
   }
}
 
public struct ChestSetNameValid
{
   public Int16 ChestIndex;
   public Int16 X;
   public Int16 Y;
   public String Name;
}
