// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ChestSyncPacket : IPacket<ChestSync>
{
   public int PacketID => 33;
   public ChestSync Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 chestIndex = reader.ReadInt16();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Byte interactionId = reader.ReadByte();

       String chestNewName = (interactionId > 0 && interactionId <= 20) ? reader.ReadString() : String.Empty;
       
       return new()
       {
           ChestIndex = chestIndex,
           X = x,
           Y = y,
           InteractionId = interactionId,
           ChestNewName = chestNewName,
       };
   }
   public byte[] Serialize(ChestSync data)
   {
       return new PacketWriter().SetType(33)
           .PackInt16(data.ChestIndex)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackByte(data.InteractionId)
           .PackString(data.ChestNewName)
           .BuildPacket();
   }
}
 
public struct ChestSync
{
   public Int16 ChestIndex;
   public Int16 X;
   public Int16 Y;
   public Byte InteractionId;
   public String ChestNewName;
}
