// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


using Microsoft.Xna.Framework;

namespace Ruby.Network.Comfortable.Packets;

internal class CombatTextPacket : IPacket<CombatText>
{
   public int PacketID => 119;
   public CombatText Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Single x = reader.ReadSingle();
       Single y = reader.ReadSingle();
       Color color = reader.ReadColor();
       Byte textMode = reader.ReadByte();
       String text = reader.ReadString();
       
       return new()
       {
           X = x,
           Y = y,
           Color = color,
           TextMode = textMode,
           Text = text,
       };
   }
   public byte[] Serialize(CombatText data)
   {
       return new PacketWriter().SetType(119)
           .PackSingle(data.X)
           .PackSingle(data.Y)
           .PackColor(data.Color)
           .PackByte(data.TextMode)
           .PackString(data.Text)
           .BuildPacket();
   }
}
 
public struct CombatText
{
   public Single X;
   public Single Y;
   public Color Color;
   public Byte TextMode;
   public String Text;
}
