// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ConnectRequestPacket : IPacket<ConnectRequest>
{
   public int PacketID => 1;

   public ConnectRequest Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       String protocolVersion = reader.ReadString();
       
       return new()
       {
           ProtocolVersion = protocolVersion,
       };
   }
   public byte[] Serialize(ConnectRequest data)
   {
       return new PacketWriter().SetType(1)
           .PackString(data.ProtocolVersion)
           .BuildPacket();
   }
}
 
public struct ConnectRequest
{
   public String ProtocolVersion;
}
