// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class DisconnectPacket : IPacket<Disconnect>
{
   public int PacketID => 2;

   public Disconnect Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte textMode = reader.ReadByte();
       String text = reader.ReadString();
       
       return new()
       {
           TextMode = textMode,
           Text = text,
       };
   }
   public byte[] Serialize(Disconnect data)
   {
       return new PacketWriter().SetType(2)
           .PackByte(data.TextMode)
           .PackString(data.Text)
           .BuildPacket();
   }
}
 
public struct Disconnect
{
   public Byte TextMode;
   public String Text;
}
