// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


using Microsoft.Xna.Framework;

namespace Ruby.Network.Comfortable.Packets;

internal class EntityTeleportPacket : IPacket<EntityTeleport>
{
   public int PacketID => 65;
   public EntityTeleport Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte flags = reader.ReadByte();
       Int16 entityIndex = reader.ReadInt16();
       Vector2 position = reader.ReadVector2();
       Byte style = reader.ReadByte();
       
       return new()
       {
           Flags = flags,
           EntityIndex = entityIndex,
           Position = position,
           Style = style,
       };
   }
   public byte[] Serialize(EntityTeleport data)
   {
       return new PacketWriter().SetType(65)
           .PackByte(data.Flags)
           .PackInt16(data.EntityIndex)
           .PackVector2(data.Position)
           .PackByte(data.Style)
           .BuildPacket();
   }
}
 
public struct EntityTeleport
{
   public Byte Flags;
   public Int16 EntityIndex;
   public Vector2 Position;
   public Byte Style;
}
