// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class InvasionReportProgressPacket : IPacket<InvasionReportProgress>
{
   public int PacketID => 78;
   public InvasionReportProgress Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int32 progress = reader.ReadInt32();
       Int32 progressMax = reader.ReadInt32();
       SByte iconId = reader.ReadSByte();
       SByte wave = reader.ReadSByte();
       
       return new()
       {
           Progress = progress,
           ProgressMax = progressMax,
           IconId = iconId,
           Wave = wave,
       };
   }
   public byte[] Serialize(InvasionReportProgress data)
   {
       return new PacketWriter().SetType(78)
           .PackInt32(data.Progress)
           .PackInt32(data.ProgressMax)
           .PackSByte(data.IconId)
           .PackSByte(data.Wave)
           .BuildPacket();
   }
}
 
public struct InvasionReportProgress
{
   public Int32 Progress;
   public Int32 ProgressMax;
   public SByte IconId;
   public SByte Wave;
}
