// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ItemOwnerPacket : IPacket<ItemOwner>
{
   public int PacketID => 22;
   public ItemOwner Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 itemIndex = reader.ReadInt16();
       Byte playerIndex = reader.ReadByte();
       
       return new()
       {
           ItemIndex = itemIndex,
           PlayerIndex = playerIndex,
       };
   }
   public byte[] Serialize(ItemOwner data)
   {
       return new PacketWriter().SetType(22)
           .PackInt16(data.ItemIndex)
           .PackByte(data.PlayerIndex)
           .BuildPacket();
   }
}
 
public struct ItemOwner
{
   public Int16 ItemIndex;
   public Byte PlayerIndex;
}
