// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


using Microsoft.Xna.Framework;

namespace Ruby.Network.Comfortable.Packets;

internal class ItemUpdateShimmerPacket : IPacket<ItemUpdateShimmer>
{
   public int PacketID => 145;
   public ItemUpdateShimmer Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 itemIndex = reader.ReadInt16();
       Vector2 position = reader.ReadVector2();
       Vector2 velocity = reader.ReadVector2();
       Int16 itemStack = reader.ReadInt16();
       Byte itemPrefix = reader.ReadByte();
       Byte ownIgnore = reader.ReadByte();
       Int16 itemType = reader.ReadInt16();
       Boolean shimmered = reader.ReadBoolean();
       Single shimmerTime = reader.ReadSingle();
       
       return new()
       {
           ItemIndex = itemIndex,
           Position = position,
           Velocity = velocity,
           ItemStack = itemStack,
           ItemPrefix = itemPrefix,
           OwnIgnore = ownIgnore,
           ItemType = itemType,
           Shimmered = shimmered,
           ShimmerTime = shimmerTime,
       };
   }
   public byte[] Serialize(ItemUpdateShimmer data)
   {
       return new PacketWriter().SetType(145)
           .PackInt16(data.ItemIndex)
           .PackVector2(data.Position)
           .PackVector2(data.Velocity)
           .PackInt16(data.ItemStack)
           .PackByte(data.ItemPrefix)
           .PackByte(data.OwnIgnore)
           .PackInt16(data.ItemType)
           .PackBoolean(data.Shimmered)
           .PackSingle(data.ShimmerTime)
           .BuildPacket();
   }
}
 
public struct ItemUpdateShimmer
{
   public Int16 ItemIndex;
   public Vector2 Position;
   public Vector2 Velocity;
   public Int16 ItemStack;
   public Byte ItemPrefix;
   public Byte OwnIgnore;
   public Int16 ItemType;
   public Boolean Shimmered;
   public Single ShimmerTime;
}
