// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


using Microsoft.Xna.Framework;

namespace Ruby.Network.Comfortable.Packets;

internal class ItemUpdateV2Packet : IPacket<ItemUpdateV2>
{
   public int PacketID => 90;
   public ItemUpdateV2 Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 itemIndex = reader.ReadInt16();
       Vector2 position = reader.ReadVector2();
       Vector2 velocity = reader.ReadVector2();
       Int16 itemStack = reader.ReadInt16();
       Byte itemPrefix = reader.ReadByte();
       Byte ownIgnore = reader.ReadByte();
       Int16 itemType = reader.ReadInt16();
       
       return new()
       {
           ItemIndex = itemIndex,
           Position = position,
           Velocity = velocity,
           ItemStack = itemStack,
           ItemPrefix = itemPrefix,
           OwnIgnore = ownIgnore,
           ItemType = itemType,
       };
   }
   public byte[] Serialize(ItemUpdateV2 data)
   {
       return new PacketWriter().SetType(90)
           .PackInt16(data.ItemIndex)
           .PackVector2(data.Position)
           .PackVector2(data.Velocity)
           .PackInt16(data.ItemStack)
           .PackByte(data.ItemPrefix)
           .PackByte(data.OwnIgnore)
           .PackInt16(data.ItemType)
           .BuildPacket();
   }
}
 
public struct ItemUpdateV2
{
   public Int16 ItemIndex;
   public Vector2 Position;
   public Vector2 Velocity;
   public Int16 ItemStack;
   public Byte ItemPrefix;
   public Byte OwnIgnore;
   public Int16 ItemType;
}
