// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcAddBuffPacket : IPacket<NpcAddBuff>
{
   public int PacketID => 53;
   public NpcAddBuff Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       UInt16 buffType = reader.ReadUInt16();
       Int16 buffDuration = reader.ReadInt16();
       
       return new()
       {
           NpcIndex = npcIndex,
           BuffType = buffType,
           BuffDuration = buffDuration,
       };
   }
   public byte[] Serialize(NpcAddBuff data)
   {
       return new PacketWriter().SetType(53)
           .PackInt16(data.NpcIndex)
           .PackUInt16(data.BuffType)
           .PackInt16(data.BuffDuration)
           .BuildPacket();
   }
}
 
public struct NpcAddBuff
{
   public Int16 NpcIndex;
   public UInt16 BuffType;
   public Int16 BuffDuration;
}
