// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcCatchPacket : IPacket<NpcCatch>
{
   public int PacketID => 70;
   public NpcCatch Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       Byte who = reader.ReadByte();
       
       return new()
       {
           NpcIndex = npcIndex,
           Who = who,
       };
   }
   public byte[] Serialize(NpcCatch data)
   {
       return new PacketWriter().SetType(70)
           .PackInt16(data.NpcIndex)
           .PackByte(data.Who)
           .BuildPacket();
   }
}
 
public struct NpcCatch
{
   public Int16 NpcIndex;
   public Byte Who;
}
