// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcEventPacket : IPacket<NpcEvent>
{
   public int PacketID => 51;
   public NpcEvent Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte npcIndex = reader.ReadByte();
       Byte actionType = reader.ReadByte();
       
       return new()
       {
           NpcIndex = npcIndex,
           ActionType = actionType,
       };
   }
   public byte[] Serialize(NpcEvent data)
   {
       return new PacketWriter().SetType(51)
           .PackByte(data.NpcIndex)
           .PackByte(data.ActionType)
           .BuildPacket();
   }
}
 
public struct NpcEvent
{
   public Byte NpcIndex;
   public Byte ActionType;
}
