// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcFishOutPacket : IPacket<NpcFishOut>
{
   public int PacketID => 130;
   public NpcFishOut Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       UInt16 x = reader.ReadUInt16();
       UInt16 y = reader.ReadUInt16();
       Int16 npcType = reader.ReadInt16();
       
       return new()
       {
           X = x,
           Y = y,
           NpcType = npcType,
       };
   }
   public byte[] Serialize(NpcFishOut data)
   {
       return new PacketWriter().SetType(130)
           .PackUInt16(data.X)
           .PackUInt16(data.Y)
           .PackInt16(data.NpcType)
           .BuildPacket();
   }
}
 
public struct NpcFishOut
{
   public UInt16 X;
   public UInt16 Y;
   public Int16 NpcType;
}
