// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcKillCountPacket : IPacket<NpcKillCount>
{
   public int PacketID => 83;
   public NpcKillCount Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 index = reader.ReadInt16();
       Int32 count = reader.ReadInt32();
       
       return new()
       {
           Index = index,
           Count = count,
       };
   }
   public byte[] Serialize(NpcKillCount data)
   {
       return new PacketWriter().SetType(83)
           .PackInt16(data.Index)
           .PackInt32(data.Count)
           .BuildPacket();
   }
}
 
public struct NpcKillCount
{
   public Int16 Index;
   public Int32 Count;
}
