// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcNamePacket : IPacket<NpcName>
{
   public int PacketID => 56;
   public NpcName Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       String name = reader.ReadString();
       Int32 variationIndex = reader.ReadInt32();
       
       return new()
       {
           NpcIndex = npcIndex,
           Name = name,
           VariationIndex = variationIndex,
       };
   }
   public byte[] Serialize(NpcName data)
   {
       return new PacketWriter().SetType(56)
           .PackInt16(data.NpcIndex)
           .PackString(data.Name)
           .PackInt32(data.VariationIndex)
           .BuildPacket();
   }
}
 
public struct NpcName
{
   public Int16 NpcIndex;
   public String Name;
   public Int32 VariationIndex;
}
