// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcRemoveBuffPacket : IPacket<NpcRemoveBuff>
{
   public int PacketID => 137;
   public NpcRemoveBuff Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       UInt16 buffType = reader.ReadUInt16();
       
       return new()
       {
           NpcIndex = npcIndex,
           BuffType = buffType,
       };
   }
   public byte[] Serialize(NpcRemoveBuff data)
   {
       return new PacketWriter().SetType(137)
           .PackInt16(data.NpcIndex)
           .PackUInt16(data.BuffType)
           .BuildPacket();
   }
}
 
public struct NpcRemoveBuff
{
   public Int16 NpcIndex;
   public UInt16 BuffType;
}
