// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcReleasePacket : IPacket<NpcRelease>
{
   public int PacketID => 71;
   public NpcRelease Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int32 x = reader.ReadInt32();
       Int32 y = reader.ReadInt32();
       Int16 type = reader.ReadInt16();
       Byte style = reader.ReadByte();
       
       return new()
       {
           X = x,
           Y = y,
           Type = type,
           Style = style,
       };
   }
   public byte[] Serialize(NpcRelease data)
   {
       return new PacketWriter().SetType(71)
           .PackInt32(data.X)
           .PackInt32(data.Y)
           .PackInt16(data.Type)
           .PackByte(data.Style)
           .BuildPacket();
   }
}
 
public struct NpcRelease
{
   public Int32 X;
   public Int32 Y;
   public Int16 Type;
   public Byte Style;
}
