// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcStartEventPacket : IPacket<NpcStartEvent>
{
   public int PacketID => 61;
   public NpcStartEvent Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 playerIndex = reader.ReadInt16();
       Int16 eventType = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           EventType = eventType,
       };
   }
   public byte[] Serialize(NpcStartEvent data)
   {
       return new PacketWriter().SetType(61)
           .PackInt16(data.PlayerIndex)
           .PackInt16(data.EventType)
           .BuildPacket();
   }
}
 
public struct NpcStartEvent
{
   public Int16 PlayerIndex;
   public Int16 EventType;
}
