// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcStrikeByItemPacket : IPacket<NpcStrikeByItem>
{
   public int PacketID => 24;
   public NpcStrikeByItem Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       Byte playerIndex = reader.ReadByte();
       
       return new()
       {
           NpcIndex = npcIndex,
           PlayerIndex = playerIndex,
       };
   }
   public byte[] Serialize(NpcStrikeByItem data)
   {
       return new PacketWriter().SetType(24)
           .PackInt16(data.NpcIndex)
           .PackByte(data.PlayerIndex)
           .BuildPacket();
   }
}
 
public struct NpcStrikeByItem
{
   public Int16 NpcIndex;
   public Byte PlayerIndex;
}
