// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class NpcSetRoomPacket : IPacket<NpcSetRoom>
{
   public int PacketID => 60;
   public NpcSetRoom Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 npcIndex = reader.ReadInt16();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Byte interactionType = reader.ReadByte();
       
       return new()
       {
           NpcIndex = npcIndex,
           X = x,
           Y = y,
           InteractionType = interactionType,
       };
   }
   public byte[] Serialize(NpcSetRoom data)
   {
       return new PacketWriter().SetType(60)
           .PackInt16(data.NpcIndex)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackByte(data.InteractionType)
           .BuildPacket();
   }
}
 
public struct NpcSetRoom
{
   public Int16 NpcIndex;
   public Int16 X;
   public Int16 Y;
   public Byte InteractionType;
}
