// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PasswordClientPacket : IPacket<PasswordClient>
{
   public int PacketID => 37;
   public PasswordClient Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       
       return new()
       {
       };
   }
   public byte[] Serialize(PasswordClient data)
   {
       return new PacketWriter().SetType(37)
           .BuildPacket();
   }
}
 
public struct PasswordClient
{
}
