// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PasswordServerPacket : IPacket<PasswordServer>
{
   public int PacketID => 38;
   public PasswordServer Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       String enteredPassword = reader.ReadString();
       
       return new()
       {
           EnteredPassword = enteredPassword,
       };
   }
   public byte[] Serialize(PasswordServer data)
   {
       return new PacketWriter().SetType(38)
           .PackString(data.EnteredPassword)
           .BuildPacket();
   }
}
 
public struct PasswordServer
{
   public String EnteredPassword;
}
