// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlaceTileEntityPacket : IPacket<PlaceTileEntity>
{
   public int PacketID => 86;
   public PlaceTileEntity Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int32 id = reader.ReadInt32();
       
       return new()
       {
           Id = id,
       };
   }
   public byte[] Serialize(PlaceTileEntity data)
   {
       return new PacketWriter().SetType(86)
           .PackInt32(data.Id)
           .BuildPacket();
   }
}
 
public struct PlaceTileEntity
{
   public Int32 Id;
}
