// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerManaHealEffectPacket : IPacket<PlayerManaHealEffect>
{
   public int PacketID => 43;
   public PlayerManaHealEffect Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 count = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Count = count,
       };
   }
   public byte[] Serialize(PlayerManaHealEffect data)
   {
       return new PacketWriter().SetType(43)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.Count)
           .BuildPacket();
   }
}
 
public struct PlayerManaHealEffect
{
   public Byte PlayerIndex;
   public Int16 Count;
}
