// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerUUIDPacket : IPacket<PlayerUUID>
{
   public int PacketID => 68;
   public PlayerUUID Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       String uuid = reader.ReadString();
       
       return new()
       {
           Uuid = uuid,
       };
   }
   public byte[] Serialize(PlayerUUID data)
   {
       return new PacketWriter().SetType(68)
           .PackString(data.Uuid)
           .BuildPacket();
   }
}
 
public struct PlayerUUID
{
   public String Uuid;
}
