// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerTeleportByItemPacket : IPacket<PlayerTeleportByItem>
{
   public int PacketID => 73;
   public PlayerTeleportByItem Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte teleportationType = reader.ReadByte();
       
       return new()
       {
           TeleportationType = teleportationType,
       };
   }
   public byte[] Serialize(PlayerTeleportByItem data)
   {
       return new PacketWriter().SetType(73)
           .PackByte(data.TeleportationType)
           .BuildPacket();
   }
}
 
public struct PlayerTeleportByItem
{
   public Byte TeleportationType;
}
