// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerLifePacket : IPacket<PlayerLife>
{
   public int PacketID => 16;
   public PlayerLife Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 life = reader.ReadInt16();
       Int16 lifeMax = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Life = life,
           LifeMax = lifeMax,
       };
   }
   public byte[] Serialize(PlayerLife data)
   {
       return new PacketWriter().SetType(16)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.Life)
           .PackInt16(data.LifeMax)
           .BuildPacket();
   }
}
 
public struct PlayerLife
{
   public Byte PlayerIndex;
   public Int16 Life;
   public Int16 LifeMax;
}
