// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerHealEffectPacket : IPacket<PlayerHealEffect>
{
   public int PacketID => 35;
   public PlayerHealEffect Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 count = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Count = count,
       };
   }
   public byte[] Serialize(PlayerHealEffect data)
   {
       return new PacketWriter().SetType(35)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.Count)
           .BuildPacket();
   }
}
 
public struct PlayerHealEffect
{
   public Byte PlayerIndex;
   public Int16 Count;
}
