// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerTogglePvPPacket : IPacket<PlayerTogglePvP>
{
   public int PacketID => 30;
   public PlayerTogglePvP Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Boolean state = reader.ReadBoolean();
       
       return new()
       {
           PlayerIndex = playerIndex,
           State = state,
       };
   }
   public byte[] Serialize(PlayerTogglePvP data)
   {
       return new PacketWriter().SetType(30)
           .PackByte(data.PlayerIndex)
           .PackBoolean(data.State)
           .BuildPacket();
   }
}
 
public struct PlayerTogglePvP
{
   public Byte PlayerIndex;
   public Boolean State;
}
