// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerLuckPacket : IPacket<PlayerLuck>
{
   public int PacketID => 134;
   public PlayerLuck Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int32 ladyBugLuckTimeLeft = reader.ReadInt32();
       Single torchLuck = reader.ReadSingle();
       Byte luckPotion = reader.ReadByte();
       Boolean gardenGnomeNearby = reader.ReadBoolean();
       Single equipmentLuckBonus = reader.ReadSingle();
       Single coinLuck = reader.ReadSingle();
       
       return new()
       {
           PlayerIndex = playerIndex,
           LadyBugLuckTimeLeft = ladyBugLuckTimeLeft,
           TorchLuck = torchLuck,
           LuckPotion = luckPotion,
           GardenGnomeNearby = gardenGnomeNearby,
           EquipmentLuckBonus = equipmentLuckBonus,
           CoinLuck = coinLuck,
       };
   }
   public byte[] Serialize(PlayerLuck data)
   {
       return new PacketWriter().SetType(134)
           .PackByte(data.PlayerIndex)
           .PackInt32(data.LadyBugLuckTimeLeft)
           .PackSingle(data.TorchLuck)
           .PackByte(data.LuckPotion)
           .PackBoolean(data.GardenGnomeNearby)
           .PackSingle(data.EquipmentLuckBonus)
           .PackSingle(data.CoinLuck)
           .BuildPacket();
   }
}
 
public struct PlayerLuck
{
   public Byte PlayerIndex;
   public Int32 LadyBugLuckTimeLeft;
   public Single TorchLuck;
   public Byte LuckPotion;
   public Boolean GardenGnomeNearby;
   public Single EquipmentLuckBonus;
   public Single CoinLuck;
}
