// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerActivePacket : IPacket<PlayerActive>
{
   public int PacketID => 14;
   public PlayerActive Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Boolean isActive = reader.ReadByte() == 1;
       
       return new()
       {
           PlayerIndex = playerIndex,
           IsActive = isActive,
       };
   }
   public byte[] Serialize(PlayerActive data)
   {
       return new PacketWriter().SetType(14)
           .PackByte(data.PlayerIndex)
           .PackByte((byte)(data.IsActive ? 1 : 0))
           .BuildPacket();
   }
}
 
public struct PlayerActive
{
   public Byte PlayerIndex;
   public Boolean IsActive;
}
