// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerDodgePacket : IPacket<PlayerDodge>
{
   public int PacketID => 62;
   public PlayerDodge Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Byte dodgeType = reader.ReadByte();
       
       return new()
       {
           PlayerIndex = playerIndex,
           DodgeType = dodgeType,
       };
   }
   public byte[] Serialize(PlayerDodge data)
   {
       return new PacketWriter().SetType(62)
           .PackByte(data.PlayerIndex)
           .PackByte(data.DodgeType)
           .BuildPacket();
   }
}
 
public struct PlayerDodge
{
   public Byte PlayerIndex;
   public Byte DodgeType;
}
