// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerPlaySoundPacket : IPacket<PlayerPlaySound>
{
   public int PacketID => 58;
   public PlayerPlaySound Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Single level = reader.ReadSingle();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Level = level,
       };
   }
   public byte[] Serialize(PlayerPlaySound data)
   {
       return new PacketWriter().SetType(58)
           .PackByte(data.PlayerIndex)
           .PackSingle(data.Level)
           .BuildPacket();
   }
}
 
public struct PlayerPlaySound
{
   public Byte PlayerIndex;
   public Single Level;
}
