// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerSyncedSpawnPacket : IPacket<PlayerSyncedSpawn>
{
   public int PacketID => 49;
   public PlayerSyncedSpawn Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       
       return new()
       {
       };
   }
   public byte[] Serialize(PlayerSyncedSpawn data)
   {
       return new PacketWriter().SetType(49)
           .BuildPacket();
   }
}
 
public struct PlayerSyncedSpawn
{
}
