// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerSetTeamPacket : IPacket<PlayerSetTeam>
{
   public int PacketID => 45;
   public PlayerSetTeam Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Byte teamId = reader.ReadByte();
       
       return new()
       {
           PlayerIndex = playerIndex,
           TeamId = teamId,
       };
   }
   public byte[] Serialize(PlayerSetTeam data)
   {
       return new PacketWriter().SetType(45)
           .PackByte(data.PlayerIndex)
           .PackByte(data.TeamId)
           .BuildPacket();
   }
}
 
public struct PlayerSetTeam
{
   public Byte PlayerIndex;
   public Byte TeamId;
}
