// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerStealthPacket : IPacket<PlayerStealth>
{
   public int PacketID => 84;
   public PlayerStealth Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Single stealth = reader.ReadSingle();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Stealth = stealth,
       };
   }
   public byte[] Serialize(PlayerStealth data)
   {
       return new PacketWriter().SetType(84)
           .PackByte(data.PlayerIndex)
           .PackSingle(data.Stealth)
           .BuildPacket();
   }
}
 
public struct PlayerStealth
{
   public Byte PlayerIndex;
   public Single Stealth;
}
