// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerAnglerQuestUpdatePacket : IPacket<PlayerAnglerQuestUpdate>
{
   public int PacketID => 74;
   public PlayerAnglerQuestUpdate Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte anglerQuest = reader.ReadByte();
       Boolean isFinisihed = reader.ReadBoolean();
       
       return new()
       {
           AnglerQuest = anglerQuest,
           IsFinisihed = isFinisihed,
       };
   }
   public byte[] Serialize(PlayerAnglerQuestUpdate data)
   {
       return new PacketWriter().SetType(74)
           .PackByte(data.AnglerQuest)
           .PackBoolean(data.IsFinisihed)
           .BuildPacket();
   }
}
 
public struct PlayerAnglerQuestUpdate
{
   public Byte AnglerQuest;
   public Boolean IsFinisihed;
}
