// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerAddBuffPacket : IPacket<PlayerAddBuff>
{
   public int PacketID => 55;
   public PlayerAddBuff Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       UInt16 buffType = reader.ReadUInt16();
       Int16 buffDuration = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           BuffType = buffType,
           BuffDuration = buffDuration,
       };
   }
   public byte[] Serialize(PlayerAddBuff data)
   {
       return new PacketWriter().SetType(55)
           .PackByte(data.PlayerIndex)
           .PackUInt16(data.BuffType)
           .PackInt16(data.BuffDuration)
           .BuildPacket();
   }
}
 
public struct PlayerAddBuff
{
   public Byte PlayerIndex;
   public UInt16 BuffType;
   public Int16 BuffDuration;
}
