// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerTalkNpcPacket : IPacket<PlayerTalkNpc>
{
   public int PacketID => 40;
   public PlayerTalkNpc Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 npcIndex = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           NpcIndex = npcIndex,
       };
   }
   public byte[] Serialize(PlayerTalkNpc data)
   {
       return new PacketWriter().SetType(40)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.NpcIndex)
           .BuildPacket();
   }
}
 
public struct PlayerTalkNpc
{
   public Byte PlayerIndex;
   public Int16 NpcIndex;
}
