// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerFinishAnglerQuestPacket : IPacket<PlayerFinishAnglerQuest>
{
   public int PacketID => 75;
   public PlayerFinishAnglerQuest Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       
       return new()
       {
       };
   }
   public byte[] Serialize(PlayerFinishAnglerQuest data)
   {
       return new PacketWriter().SetType(75)
           .BuildPacket();
   }
}
 
public struct PlayerFinishAnglerQuest
{
}
