// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerSpawnPacket : IPacket<PlayerSpawn>
{
   public int PacketID => 12;
   public PlayerSpawn Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 spawnX = reader.ReadInt16();
       Int16 spawnY = reader.ReadInt16();
       Int32 respawnTimer = reader.ReadInt32();
       Int16 deathsPvE = reader.ReadInt16();
       Int16 deathsPvP = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           SpawnX = spawnX,
           SpawnY = spawnY,
           RespawnTimer = respawnTimer,
           DeathsPvE = deathsPvE,
           DeathsPvP = deathsPvP,
       };
   }
   public byte[] Serialize(PlayerSpawn data)
   {
       return new PacketWriter().SetType(12)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.SpawnX)
           .PackInt16(data.SpawnY)
           .PackInt32(data.RespawnTimer)
           .PackInt16(data.DeathsPvE)
           .PackInt16(data.DeathsPvP)
           .BuildPacket();
   }
}
 
public struct PlayerSpawn
{
   public Byte PlayerIndex;
   public Int16 SpawnX;
   public Int16 SpawnY;
   public Int32 RespawnTimer;
   public Int16 DeathsPvE;
   public Int16 DeathsPvP;
}
