// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerAnimationPacket : IPacket<PlayerAnimation>
{
   public int PacketID => 41;
   public PlayerAnimation Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Single itemRotation = reader.ReadSingle();
       Int16 itemAnimation = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           ItemRotation = itemRotation,
           ItemAnimation = itemAnimation,
       };
   }
   public byte[] Serialize(PlayerAnimation data)
   {
       return new PacketWriter().SetType(41)
           .PackByte(data.PlayerIndex)
           .PackSingle(data.ItemRotation)
           .PackInt16(data.ItemAnimation)
           .BuildPacket();
   }
}
 
public struct PlayerAnimation
{
   public Byte PlayerIndex;
   public Single ItemRotation;
   public Int16 ItemAnimation;
}
