// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerPlaceItemPacket : IPacket<PlayerPlaceItem>
{
   public int PacketID => 85;
   public PlayerPlaceItem Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 slot = reader.ReadInt16();
       
       return new()
       {
           Slot = slot,
       };
   }
   public byte[] Serialize(PlayerPlaceItem data)
   {
       return new PacketWriter().SetType(85)
           .PackInt16(data.Slot)
           .BuildPacket();
   }
}
 
public struct PlayerPlaceItem
{
   public Int16 Slot;
}
