// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerSlotPacket : IPacket<PlayerSlot>
{
   public int PacketID => 5;
   public PlayerSlot Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 slotIndex = reader.ReadInt16();
       Int16 itemStack = reader.ReadInt16();
       Byte itemPrefix = reader.ReadByte();
       Int16 itemType = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           SlotIndex = slotIndex,
           ItemStack = itemStack,
           ItemPrefix = itemPrefix,
           ItemType = itemType,
       };
   }
   public byte[] Serialize(PlayerSlot data)
   {
       return new PacketWriter().SetType(5)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.SlotIndex)
           .PackInt16(data.ItemStack)
           .PackByte(data.ItemPrefix)
           .PackInt16(data.ItemType)
           .BuildPacket();
   }
}
 
public struct PlayerSlot
{
   public Byte PlayerIndex;
   public Int16 SlotIndex;
   public Int16 ItemStack;
   public Byte ItemPrefix;
   public Int16 ItemType;
}
