// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerManaPacket : IPacket<PlayerMana>
{
   public int PacketID => 42;
   public PlayerMana Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 mana = reader.ReadInt16();
       Int16 manaMax = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           Mana = mana,
           ManaMax = manaMax,
       };
   }
   public byte[] Serialize(PlayerMana data)
   {
       return new PacketWriter().SetType(42)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.Mana)
           .PackInt16(data.ManaMax)
           .BuildPacket();
   }
}
 
public struct PlayerMana
{
   public Byte PlayerIndex;
   public Int16 Mana;
   public Int16 ManaMax;
}
