// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class PlayerHealPacket : IPacket<PlayerHeal>
{
   public int PacketID => 66;
   public PlayerHeal Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte playerIndex = reader.ReadByte();
       Int16 healCount = reader.ReadInt16();
       
       return new()
       {
           PlayerIndex = playerIndex,
           HealCount = healCount,
       };
   }
   public byte[] Serialize(PlayerHeal data)
   {
       return new PacketWriter().SetType(66)
           .PackByte(data.PlayerIndex)
           .PackInt16(data.HealCount)
           .BuildPacket();
   }
}
 
public struct PlayerHeal
{
   public Byte PlayerIndex;
   public Int16 HealCount;
}
