// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class ReadNetModulePacket : IPacket<ReadNetModule>
{
   public int PacketID => 82;
   public ReadNetModule Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       UInt16 netModuleID = reader.ReadUInt16();
       
       return new()
       {
           NetModuleID = netModuleID,
       };
   }
   public byte[] Serialize(ReadNetModule data)
   {
       return new PacketWriter().SetType(82)
           .PackUInt16(data.NetModuleID)
           .BuildPacket();
   }
}
 
public struct ReadNetModule
{
   public UInt16 NetModuleID;
}
