// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class RequestWorldInfoPacket : IPacket<RequestWorldInfo>
{
   public int PacketID => 6;

   public RequestWorldInfo Deserialize(byte[] data)
   {   
       return default;
   }

   public byte[] Serialize(RequestWorldInfo data)
   {
       return new PacketWriter().SetType(6)
           .BuildPacket();
   }
}
 
public struct RequestWorldInfo
{
}
