// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class RequestSectionPacket : IPacket<RequestSection>
{
   public int PacketID => 8;
   public RequestSection Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int32 x = reader.ReadInt32();
       Int32 y = reader.ReadInt32();
       
       return new()
       {
           X = x,
           Y = y,
       };
   }
   public byte[] Serialize(RequestSection data)
   {
       return new PacketWriter().SetType(8)
           .PackInt32(data.X)
           .PackInt32(data.Y)
           .BuildPacket();
   }
}
 
public struct RequestSection
{
   public Int32 X;
   public Int32 Y;
}
