// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class SignReadRequestPacket : IPacket<SignReadRequest>
{
   public int PacketID => 46;
   public SignReadRequest Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       
       return new()
       {
           X = x,
           Y = y,
       };
   }
   public byte[] Serialize(SignReadRequest data)
   {
       return new PacketWriter().SetType(46)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .BuildPacket();
   }
}
 
public struct SignReadRequest
{
   public Int16 X;
   public Int16 Y;
}
