// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class SignReadPacket : IPacket<SignRead>
{
   public int PacketID => 47;
   public SignRead Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 signIndex = reader.ReadInt16();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       String text = reader.ReadString();
       Byte recipient = reader.ReadByte();
       Byte uselessFlag = reader.ReadByte();
       
       return new()
       {
           SignIndex = signIndex,
           X = x,
           Y = y,
           Text = text,
           Recipient = recipient,
           UselessFlag = uselessFlag,
       };
   }
   public byte[] Serialize(SignRead data)
   {
       return new PacketWriter().SetType(47)
           .PackInt16(data.SignIndex)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackString(data.Text)
           .PackByte(data.Recipient)
           .PackByte(data.UselessFlag)
           .BuildPacket();
   }
}
 
public struct SignRead
{
   public Int16 SignIndex;
   public Int16 X;
   public Int16 Y;
   public String Text;
   public Byte Recipient;
   public Byte UselessFlag;
}
