// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class StatusPacketPacket : IPacket<StatusPacket>
{
   public int PacketID => 9;
   public StatusPacket Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int32 statusMax = reader.ReadInt32();
       Byte textMode = reader.ReadByte();
       String text = reader.ReadString();
       Byte flags = reader.ReadByte();
       
       return new()
       {
           StatusMax = statusMax,
           TextMode = textMode,
           Text = text,
           Flags = flags,
       };
   }
   public byte[] Serialize(StatusPacket data)
   {
       return new PacketWriter().SetType(9)
           .PackInt32(data.StatusMax)
           .PackByte(data.TextMode)
           .PackString(data.Text)
           .PackByte(data.Flags)
           .BuildPacket();
   }
}
 
public struct StatusPacket
{
   public Int32 StatusMax;
   public Byte TextMode;
   public String Text;
   public Byte Flags;
}
