// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TileCreateLiquidPacket : IPacket<TileCreateLiquid>
{
   public int PacketID => 48;
   public TileCreateLiquid Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Byte liquidCount = reader.ReadByte();
       Byte liquidID = reader.ReadByte();
       
       return new()
       {
           X = x,
           Y = y,
           LiquidCount = liquidCount,
           LiquidID = liquidID,
       };
   }
   public byte[] Serialize(TileCreateLiquid data)
   {
       return new PacketWriter().SetType(48)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackByte(data.LiquidCount)
           .PackByte(data.LiquidID)
           .BuildPacket();
   }
}
 
public struct TileCreateLiquid
{
   public Int16 X;
   public Int16 Y;
   public Byte LiquidCount;
   public Byte LiquidID;
}
