// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TilePaintWallPacket : IPacket<TilePaintWall>
{
   public int PacketID => 64;
   public TilePaintWall Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Byte paintId = reader.ReadByte();
       Byte coatId = reader.ReadByte();
       
       return new()
       {
           X = x,
           Y = y,
           PaintId = paintId,
           CoatId = coatId,
       };
   }
   public byte[] Serialize(TilePaintWall data)
   {
       return new PacketWriter().SetType(64)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackByte(data.PaintId)
           .PackByte(data.CoatId)
           .BuildPacket();
   }
}
 
public struct TilePaintWall
{
   public Int16 X;
   public Int16 Y;
   public Byte PaintId;
   public Byte CoatId;
}
