// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TileLockSomethingPacket : IPacket<TileLockSomething>
{
   public int PacketID => 52;
   public TileLockSomething Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte target = reader.ReadByte();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       
       return new()
       {
           Target = target,
           X = x,
           Y = y,
       };
   }
   public byte[] Serialize(TileLockSomething data)
   {
       return new PacketWriter().SetType(52)
           .PackByte(data.Target)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .BuildPacket();
   }
}
 
public struct TileLockSomething
{
   public Byte Target;
   public Int16 X;
   public Int16 Y;
}
