// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


using Ruby.Network.Comfortable.Structures;

namespace Ruby.Network.Comfortable.Packets;

internal class TileRectanglePacket : IPacket<TileRectangle>
{
   public int PacketID => 20;
   public TileRectangle Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Byte width = reader.ReadByte();
       Byte height = reader.ReadByte();
       Byte tileChangeType = reader.ReadByte();

        NetTile[,] tiles = new NetTile[width, height];

        for (int i = 0; i < width; i++)
        for (int j = 0; j < height; j++)
            tiles[i, j] = new NetTile(reader);
       
       return new()
       {
           X = x,
           Y = y,
           Width = width,
           Height = height,
           TileChangeType = tileChangeType,
           Tiles = tiles,
       };
   }
   public byte[] Serialize(TileRectangle data)
   {
       var packet = new PacketWriter().SetType(20)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackByte(data.Width)
           .PackByte(data.Height)
           .PackByte(data.TileChangeType);
        
        foreach (NetTile tile in data.Tiles)
            tile.Serialize(ref packet);

        return packet.BuildPacket();
   }
}
 
public struct TileRectangle
{
   public Int16 X;
   public Int16 Y;
   public Byte Width;
   public Byte Height;
   public Byte TileChangeType;
   public NetTile[,] Tiles;
}
