// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TileDoorInteractPacket : IPacket<TileDoorInteract>
{
   public int PacketID => 19;
   public TileDoorInteract Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte interaction = reader.ReadByte();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       
       return new()
       {
           Interaction = interaction,
           X = x,
           Y = y,
       };
   }
   public byte[] Serialize(TileDoorInteract data)
   {
       return new PacketWriter().SetType(19)
           .PackByte(data.Interaction)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .BuildPacket();
   }
}
 
public struct TileDoorInteract
{
   public Byte Interaction;
   public Int16 X;
   public Int16 Y;
}
