// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TileFoodPlatterPlacePacket : IPacket<TileFoodPlatterPlace>
{
   public int PacketID => 133;
   public TileFoodPlatterPlace Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Int16 itemType = reader.ReadInt16();
       Byte itemPrefix = reader.ReadByte();
       Int16 itemStack = reader.ReadInt16();
       
       return new()
       {
           X = x,
           Y = y,
           ItemType = itemType,
           ItemPrefix = itemPrefix,
           ItemStack = itemStack,
       };
   }
   public byte[] Serialize(TileFoodPlatterPlace data)
   {
       return new PacketWriter().SetType(133)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackInt16(data.ItemType)
           .PackByte(data.ItemPrefix)
           .PackInt16(data.ItemStack)
           .BuildPacket();
   }
}
 
public struct TileFoodPlatterPlace
{
   public Int16 X;
   public Int16 Y;
   public Int16 ItemType;
   public Byte ItemPrefix;
   public Int16 ItemStack;
}
