// Terraria SDK CodeGen
// This code was generated by the program, and it's normally if there are warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TilePlaceObjectPacket : IPacket<TilePlaceObject>
{
   public int PacketID => 79;
   public TilePlaceObject Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Int16 type = reader.ReadInt16();
       Int16 style = reader.ReadInt16();
       Byte alternate = reader.ReadByte();
       SByte random = reader.ReadSByte();
       Boolean direction = reader.ReadBoolean();
       
       return new()
       {
           X = x,
           Y = y,
           Type = type,
           Style = style,
           Alternate = alternate,
           Random = random,
           Direction = direction,
       };
   }
   public byte[] Serialize(TilePlaceObject data)
   {
       return new PacketWriter().SetType(79)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackInt16(data.Type)
           .PackInt16(data.Style)
           .PackByte(data.Alternate)
           .PackSByte(data.Random)
           .PackBoolean(data.Direction)
           .BuildPacket();
   }
}
 
public struct TilePlaceObject
{
   public Int16 X;
   public Int16 Y;
   public Int16 Type;
   public Int16 Style;
   public Byte Alternate;
   public SByte Random;
   public Boolean Direction;
}
