// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class TileInteractPacket : IPacket<TileInteract>
{
   public int PacketID => 17;
   public TileInteract Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Byte action = reader.ReadByte();
       Int16 x = reader.ReadInt16();
       Int16 y = reader.ReadInt16();
       Int16 tileType = reader.ReadInt16();
       Byte tileStyle = reader.ReadByte();
       
       return new()
       {
           Action = action,
           X = x,
           Y = y,
           TileType = tileType,
           TileStyle = tileStyle,
       };
   }
   public byte[] Serialize(TileInteract data)
   {
       return new PacketWriter().SetType(17)
           .PackByte(data.Action)
           .PackInt16(data.X)
           .PackInt16(data.Y)
           .PackInt16(data.TileType)
           .PackByte(data.TileStyle)
           .BuildPacket();
   }
}
 
public struct TileInteract
{
   public Byte Action;
   public Int16 X;
   public Int16 Y;
   public Int16 TileType;
   public Byte TileStyle;
}
