// Terraria SDK CodeGen
// That code was generated by program and this is normally if there is warnings.


namespace Ruby.Network.Comfortable.Packets;

internal class WorldTimePacket : IPacket<WorldTime>
{
   public int PacketID => 18;
   public WorldTime Deserialize(byte[] data)
   {
       using MemoryStream stream = new MemoryStream(data);
       using BinaryReader reader = new BinaryReader(stream);
       
       Boolean isDayTime = reader.ReadByte() == 1;
       Int32 time = reader.ReadInt32();
       Int16 sunModY = reader.ReadInt16();
       Int16 moonModY = reader.ReadInt16();
       
       return new()
       {
           IsDayTime = isDayTime,
           Time = time,
           SunModY = sunModY,
           MoonModY = moonModY,
       };
   }
   public byte[] Serialize(WorldTime data)
   {
       return new PacketWriter().SetType(18)
           .PackByte((byte)(data.IsDayTime ? 1 : 0))
           .PackInt32(data.Time)
           .PackInt16(data.SunModY)
           .PackInt16(data.MoonModY)
           .BuildPacket();
   }
}
 
public struct WorldTime
{
   public Boolean IsDayTime;
   public Int32 Time;
   public Int16 SunModY;
   public Int16 MoonModY;
}
